abstract: Query job-related web search engines
author: Martin Thurn <mthurn@cpan.org>
distribution_type: module
generated_by: Module::Install version 0.52
license: perl
name: WWW-Search-Jobs
no_index:
  directory:
    - inc
    - t
requires:
  WWW::Search: 0
  perl: 5.004
version: 2.021
